title: "PSRCore"
remote_theme: pmarsceill/just-the-docs

# port: 4001

plugins:
  - jekyll-remote-theme

ga_tracking: G-0EBJYPVP12
ga_tracking_anonymize_ip: true
exclude: [node_modules]

back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy; 2021 PSR - <a href='https://www.psr-inc.com' target='_blank'>psr-inc.com</a>"