title: "PSRIO"
remote_theme: pmarsceill/just-the-docs

# aux_links:
#   "PSRIO Scripts on GitHub":
#     - "//github.com/psrenergy/psrio-scripts"

# port: 4001

plugins:
  - jekyll-remote-theme

ga_tracking: G-0EBJYPVP12
ga_tracking_anonymize_ip: true
exclude: [node_modules]

footer_content: "Copyright &copy; 2021 PSR - <a href='https://www.psr-inc.com' target='_blank'>psr-inc.com</a>"